### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by JaroSound** [Bluethefurry/EasyAdmin-MySQL#4]
`Error running call reference function for resource EasyAdmin-MySQL: citizen:/scripting/lua/scheduler.lua:405: citizen:/scripting/lua/json.lua:397: bad argument #1 to 'strfind' (string expected, got nil)
stack traceback:
	[C]: in function 'string.find'
	citizen:/scripting/lua/json.lua:397: in upvalue 'scanwhite'
	citizen:/scripting/lua/json.lua:553: in function <citizen:/scripting/lua/json.lua:551>
	(...tail calls...)
	@EasyAdmin-MySQL/server.lua:69: in upvalue 'ref'
	citizen:/scripting/lua/scheduler.lua:391: in function <citizen:/scripting/lua/scheduler.lua:390>
	[C]: in function 'xpcall'
	citizen:/scripting/lua/scheduler.lua:390: in function <citizen:/scripting/lua/scheduler.lua:389>
stack traceback:
	[C]: in function 'error'
	citizen:/scripting/lua/scheduler.lua:405: in function <citizen:/scripting/lua/scheduler.lua:374>
[91mError: Unhandled error in timer: Error: BUFFER_SHORTAGE
Error: BUFFER_SHORTAGE
    at n.e [as reserve] (citizen:/scripting/v8/msgpack.js:29:12766)
    at h (citizen:/scripting/v8/msgpack.js:29:15761)
    at n.r [as decode] (citizen:/scripting/v8/msgpack.js:29:13908)
    at n.fetch (citizen:/scripting/v8/msgpack.js:29:6972)
    at n.u [as read] (citizen:/scripting/v8/msgpack.js:29:12076)
    at Object.n [as decode] (citizen:/scripting/v8/msgpack.js:29:7097)
    at unpack (citizen:/scripting/v8/main.js:20:33)
    at citizen:/scripting/v8/main.js:51:20
    at setImmediate (mysql-async.js:14901:7)
    at Object.callback (citizen:/scripting/v8/timer.js:96:21)`

**Comment by Blumlaut** [comment]
wtf, can you reproduce this? that means that the banlist failed to upgrade

**Comment by JaroSound** [comment]
The problem appeared after the last update. 
And the same thing appears every time you start the server.

**Comment by JaroSound** [comment]
Still the same problem, the same error.

So is there another way to convert my existing "ea_bans" table to the new one without losing bans?
